services:  
  fastapi:    
    build: ./api   
    volumes:  
      - ./fastapi:/app    
    ports:     
     - 8000:8000    
    restart: always    
    tty: true    
    depends_on:   
       - db  
    
  db:    
    image: postgres:15    
    container_name: postgres-db    
    volumes:
     - postgres_data:/var/lib/postgresql/data/    
    environment:     
     - POSTGRES_USER=${USER_NAME}
     - POSTGRES_PASSWORD=${USER_PASS}
    ports:     
     - 5432:5432
  
volumes:  
  postgres_data:  